# Numpy Review

In [1]:
import numpy as np
import torch
# numpy를 이해하면 pytorch를 쉽게 접할 수 있다.


t = np.array([0., 1., 2., 3., 4., 5., 6.]) # 1d vector
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [2]:
print('Rank of t :', t.ndim)
print('Shape of t :', t.shape ) # 하나의 차원에서 7개의 엘리먼트를 갖고 있다.

Rank of t : 1
Shape of t : (7,)


In [3]:
print(t[0],t[1],t[-1]) #Element
print(t[2:5],t[4:-1]) #Slicing
print(t[:2],t[3:]) #Slicing

0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [5]:
t = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(t)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
print('Rank of t : ', t.ndim)
print('Shape of t : ', t.shape)

Rank of t :  2
Shape of t :  (4, 3)


# Pytorch Tensor

### 1D Array with PyTorch

In [7]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.]) #float 형텐서로 만듬
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [9]:
print(t.dim()) #rank
print(t.shape) #shape
print(t.size()) #shape
print(t[0], t[2])   # Element
print(t[2:5],t[4:-1])  #Slicing
print(t[:2], t[3:])    #Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(2.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2D Array with Pytorch

In [10]:
t = torch.FloatTensor([[1,2,3],
                       [4,5,6],
                       [7,8,9],
                       [10,11,12]
                      ])
print(t) #4,3 matrix

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [14]:
print(t.dim()) #rank 2개의 차원
print(t.shape) #shape
print(t.size()) #shape
print(t[:,1])
print(t[:,1].size())
print(t[:, :2])
print(t[:, :-1]) #맨마지막을 제외한것을 가져와라

2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Broadcasting

In [15]:
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print( m1 + m2 )

tensor([[5., 5.]])


In [16]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])
print( m1 + m2 )

tensor([[4., 5.]])


In [18]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2 ]])
m2 = torch.FloatTensor([[3],[4]])
print( m1 + m2 )

tensor([[4., 5.],
        [5., 6.]])


위의 경우 같이 브로드캐스팅을 사용할땐 자동으로 size를 맞춰버리므로 사용시 조심해야한다.

### Multiplication VS Matrix Multiplication

In [24]:
# 행렬곱
m1 = torch.FloatTensor([[1, 2],[3, 4]])
m2 = torch.FloatTensor([[1],[2]])
m3 = m1.matmul(m2)
print(m3)
print(m3.size())

print("\n ****************** \n")

# 그냥 list곱
m1 = torch.FloatTensor([[1, 2],[3, 4]])
m2 = torch.FloatTensor([[1],[2]])
m4 = m1*m2 # 여기선 자동으로 m2를 [[1,1],[2,2]]로 만들어 버림
print(m4)
print(m1.mul(m2))

tensor([[ 5.],
        [11.]])
torch.Size([2, 1])

 ****************** 

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### Mean

In [25]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [26]:
# LongTensor에선 또 안됌
t = torch.LongTensor([1,2])
try : 
    print(t.mean())
except Exception as exc :
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [28]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t.mean()) #전체 4개 엘레먼트에 대해
print(t.mean(dim=0)) #첫번째 dim에대해서만 2x2 에서 dim=0을했으니깐 1x2행렬이된다 
print(t.mean(dim=1)) #2x1 행렬로평균값으로 만든다
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### Sum

In [30]:
"""
[[1,2]
[3,4]]
"""

print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max and ArgMax
멕스는 텐서나 행렬에서 가장값을 리턴해주고,  
ArgMax 는 그 인덱스 값을 리턴해줍니다.

In [31]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


The max operator returns one value if it is called without an argument

In [32]:
print(t.max())

tensor(4.)


The max operator return 2 values when called dimention specified. The first value is the maximum value, and the second value is the argmax: the index of the element with maximum value

In [34]:
print(t.max(dim=0))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [35]:
print(t.max(dim=1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
