In [7]:
import numpy as np
import torch

### View (Reshape)

In [10]:
t = np.array([[[0,1,2],
               [3,4,5]],
              
              [[6,7,8],
              [9,10,11]
              ]
             ])
ft = torch.FloatTensor(t)
print(t.shape)
print(ft.shape)
# 2,2,3 의 텐서를 만듬

(2, 2, 3)
torch.Size([2, 2, 3])


In [12]:
print(ft.view([-1,3])) # 앞에는 모르겠고 2번째 차원은 3개를 갖겠다.
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [13]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


여기서 주목할점은 tensor들의 사이즈의 곱이 전부 기존의 텐서와 같이 12인것을 알아야한다.
이 뷰함수를 통해 우리가 원하는 크기의 vector tensor를 만들수 있다.

### Squeeze

squeeze는 view를 쓰는것과 비슷하긴한데, 다른점은 자동으로 dimension의 element가 1인것을 자동으로 없애준다.

In [14]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [16]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [18]:
print(ft.T)
print(ft.T.squeeze())
print(ft.T.squeeze().shape)

tensor([[0., 1., 2.]])
tensor([0., 1., 2.])
torch.Size([3])


### Unsqueeze

In [19]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [24]:
print(ft.unsqueeze(0)) # 0즉, 첫번째 디멘션 0의 크기를 1로 만들어라
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [25]:
print(ft.view(1, -1)) # 위와 같은 결과
print(ft.view(1, -1).shape) # 뒤는 어떻게될지 모르겠고 앞에 디멘에 1값을 만들어라

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [26]:
print(ft.unsqueeze(1)) # 1즉, 두번째 디멘션 1의 크기를 1로 만들어라
print(ft.unsqueeze(1).shape) 

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [27]:
print(ft.unsqueeze(-1)) # -1즉, 마지막 디멘션의 크기를 1로 만들어라
print(ft.unsqueeze(-1).shape) 

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Type Casting
텐서의 타입을 바꾸기 위해 나옴  
masking 등에서 사용된다.

In [28]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [30]:
print(lt.float()) # float 텐서형태로 출력

tensor([1., 2., 3., 4.])


In [31]:
bt = torch.ByteTensor([True,False,True,False])
print(bt)

tensor([1, 0, 1, 0], dtype=torch.uint8)


In [32]:
bt2 = (lt == 3)
print(bt2)

tensor([False, False,  True, False])


In [33]:
print(bt.long())
print(bt.float())

tensor([1, 0, 1, 0])
tensor([1., 0., 1., 0.])


### Concatenate

In [34]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

In [35]:
print(torch.cat([x,y], dim=0)) # dimension 0 에 대해서 concat하라 (4,2)가 될것
print(torch.cat([x,y], dim=1)) # dimension 1 에 대허서 concat하라 (2,4)가 된다.

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking
concat을 좀더 쉽게 만들어준다.  
stack함수는 두가지 파라미터를 갖는다.  
첫번째 파라미터는 list는 텐서들을 받습니다.    
두번째 파라미터로 dimension을 받습니다.

In [36]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [37]:
print(torch.stack([x,y,z])) 
# x
# y
# z
# 형태로 stack이 된다. (3,2) 로 쌓인다 새로운 차원이 생김.

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [38]:
print(torch.stack([x,y,z], dim =1))
# xyz 형태로 stack이 된다.

tensor([[1., 2., 3.],
        [4., 5., 6.]])


위 형태들은 cat을 이용하여 표현하려면 이렇게 된다.

In [42]:
print(x.shape)
print(x.unsqueeze(0).shape)
# 이를 이용해 만들도록 할것입니다.

torch.Size([2])
torch.Size([1, 2])


In [44]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)]))
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [45]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 1))

tensor([[1., 4., 2., 5., 3., 6.]])


### One and Zeros

In [47]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [52]:
print(torch.ones_like(x)) # x와 동일한 크기의 텐서에 1을 채운다

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [53]:
print(torch.zeros_like(x)) # x와 동일한 크기의 텐서에 0을 채운다

tensor([[0., 0., 0.],
        [0., 0., 0.]])


위 모델은 같은 device의 텐서를 선언해준다.
cpu, gpu 가 다른곳에서 생성된 tensor들은 서로 연산 에러가 발생한다.!!  
+multiple gup에서도 발생가능성이 있음

### In-place Operation

새로운 메모리를 할당하지말고 연산을 처리하라.  
어떤 느낌인지는 아래 코드를 보고 이해하세요.

In [55]:
x = torch.FloatTensor([[1,2],[3,4]])
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x) # 완전 변수 메모리안의 값이 변경되었음,

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
